const myFriends = [{
    firstName: 'Sunflower',
    lastName: 'Sunrise',
    akaName: 'Sunset',
    age: 22
}, {
    firstName: 'Cookie&Cream',
    lastName: 'Chocalato',
    akaName: 'Softcookie',
    age: 25
}, {
    firstName: 'Whiskas',
    lastName: 'ForKitten',
    akaName: 'MeowMeow',
    age: 27
}, {
    firstName: 'DaisyDaily',
    lastName: 'LittleTiny',
    akaName: 'Adorable',
    age: 23
}]

console.log(myFriends[1])
console.log(myFriends[1].firstName)

// [LOG]: {
//     "firstName": "Cookie&Cream",
//     "lastName": "Chocalato",
//     "akaName": "Softcookie",
//     "age": 25
//   } 
// [LOG]: "Cookie&Cream" 

const myFriendsAKA = myFriends.map(function (element, index) {
    return ({
        chi: element.firstName,
        chaya: element.akaName
    })
})

const myFriendsMoreThan = myFriends.filter(function (element, index) {
    return element.age > 24 && element.lastName === 'Chocalato'
})

console.log(myFriendsMoreThan)

const database = [
    {
        "year": 2024,
        "weeknum": 34,
        "province": "บุรีรัมย์",
        "new_case": 6,
        "total_case": 578,
        "new_case_excludeabroad": 6,
        "total_case_excludeabroad": 578,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สุรินทร์",
        "new_case": 16,
        "total_case": 702,
        "new_case_excludeabroad": 16,
        "total_case_excludeabroad": 702,
        "new_death": 0,
        "total_death": 11,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ตราด",
        "new_case": 2,
        "total_case": 335,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 335,
        "new_death": 0,
        "total_death": 4,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สงขลา",
        "new_case": 10,
        "total_case": 1029,
        "new_case_excludeabroad": 10,
        "total_case_excludeabroad": 1029,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "เพชรบูรณ์",
        "new_case": 1,
        "total_case": 413,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 413,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "พิษณุโลก",
        "new_case": 13,
        "total_case": 483,
        "new_case_excludeabroad": 13,
        "total_case_excludeabroad": 483,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "กาฬสินธุ์",
        "new_case": 3,
        "total_case": 237,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 237,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ราชบุรี",
        "new_case": 5,
        "total_case": 591,
        "new_case_excludeabroad": 5,
        "total_case_excludeabroad": 591,
        "new_death": 0,
        "total_death": 7,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ระนอง",
        "new_case": 0,
        "total_case": 4,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 4,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "เชียงราย",
        "new_case": 1,
        "total_case": 188,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 188,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สตูล",
        "new_case": 0,
        "total_case": 12,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 12,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ยะลา",
        "new_case": 1,
        "total_case": 107,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 107,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ชลบุรี",
        "new_case": 12,
        "total_case": 3011,
        "new_case_excludeabroad": 12,
        "total_case_excludeabroad": 3011,
        "new_death": 0,
        "total_death": 18,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สระบุรี",
        "new_case": 3,
        "total_case": 287,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 287,
        "new_death": 0,
        "total_death": 7,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "อ่างทอง",
        "new_case": 0,
        "total_case": 136,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 136,
        "new_death": 0,
        "total_death": 5,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ระยอง",
        "new_case": 2,
        "total_case": 461,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 461,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ชัยนาท",
        "new_case": 0,
        "total_case": 45,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 45,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ประจวบคีรีขันธ์",
        "new_case": 1,
        "total_case": 240,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 240,
        "new_death": 0,
        "total_death": 4,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สกลนคร",
        "new_case": 3,
        "total_case": 81,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 81,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "นราธิวาส",
        "new_case": 0,
        "total_case": 66,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 66,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ปัตตานี",
        "new_case": 0,
        "total_case": 29,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 29,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "อำนาจเจริญ",
        "new_case": 0,
        "total_case": 48,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 48,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "พัทลุง",
        "new_case": 0,
        "total_case": 155,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 155,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ปทุมธานี",
        "new_case": 2,
        "total_case": 671,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 671,
        "new_death": 0,
        "total_death": 3,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ฉะเชิงเทรา",
        "new_case": 1,
        "total_case": 267,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 267,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "จันทบุรี",
        "new_case": 4,
        "total_case": 765,
        "new_case_excludeabroad": 4,
        "total_case_excludeabroad": 765,
        "new_death": 0,
        "total_death": 6,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "แม่ฮ่องสอน",
        "new_case": 0,
        "total_case": 41,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 41,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "นครพนม",
        "new_case": 0,
        "total_case": 145,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 145,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "แพร่",
        "new_case": 0,
        "total_case": 137,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 137,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สมุทรปราการ",
        "new_case": 3,
        "total_case": 696,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 696,
        "new_death": 0,
        "total_death": 6,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "นครนายก",
        "new_case": 0,
        "total_case": 20,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 20,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "เลย",
        "new_case": 1,
        "total_case": 477,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 477,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ขอนแก่น",
        "new_case": 10,
        "total_case": 1208,
        "new_case_excludeabroad": 10,
        "total_case_excludeabroad": 1208,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "กำแพงเพชร",
        "new_case": 3,
        "total_case": 110,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 110,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ปราจีนบุรี",
        "new_case": 1,
        "total_case": 106,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 106,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ศรีสะเกษ",
        "new_case": 1,
        "total_case": 72,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 72,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "เพชรบุรี",
        "new_case": 0,
        "total_case": 246,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 246,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สระแก้ว",
        "new_case": 1,
        "total_case": 416,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 416,
        "new_death": 0,
        "total_death": 11,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "หนองคาย",
        "new_case": 6,
        "total_case": 410,
        "new_case_excludeabroad": 6,
        "total_case_excludeabroad": 410,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "พิจิตร",
        "new_case": 4,
        "total_case": 245,
        "new_case_excludeabroad": 4,
        "total_case_excludeabroad": 245,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "อุทัยธานี",
        "new_case": 3,
        "total_case": 155,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 155,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ทั้งประเทศ",
        "new_case": 569,
        "total_case": 37922,
        "new_case_excludeabroad": 569,
        "total_case_excludeabroad": 37922,
        "new_death": 1,
        "total_death": 200,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "อุตรดิตถ์",
        "new_case": 1,
        "total_case": 215,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 215,
        "new_death": 0,
        "total_death": 5,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สุราษฎร์ธานี",
        "new_case": 10,
        "total_case": 944,
        "new_case_excludeabroad": 10,
        "total_case_excludeabroad": 944,
        "new_death": 0,
        "total_death": 9,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "กระบี่",
        "new_case": 1,
        "total_case": 192,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 192,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สุโขทัย",
        "new_case": 0,
        "total_case": 101,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 101,
        "new_death": 0,
        "total_death": 3,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สิงห์บุรี",
        "new_case": 1,
        "total_case": 163,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 163,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ยโสธร",
        "new_case": 0,
        "total_case": 183,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 183,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "พะเยา",
        "new_case": 15,
        "total_case": 299,
        "new_case_excludeabroad": 15,
        "total_case_excludeabroad": 299,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ร้อยเอ็ด",
        "new_case": 3,
        "total_case": 484,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 484,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "อุดรธานี",
        "new_case": 4,
        "total_case": 663,
        "new_case_excludeabroad": 4,
        "total_case_excludeabroad": 663,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ชัยภูมิ",
        "new_case": 2,
        "total_case": 168,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 168,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "นครศรีธรรมราช",
        "new_case": 0,
        "total_case": 669,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 669,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "พังงา",
        "new_case": 0,
        "total_case": 15,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 15,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ภูเก็ต",
        "new_case": 7,
        "total_case": 787,
        "new_case_excludeabroad": 7,
        "total_case_excludeabroad": 787,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "นนทบุรี",
        "new_case": 9,
        "total_case": 1059,
        "new_case_excludeabroad": 9,
        "total_case_excludeabroad": 1059,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ไม่ระบุ",
        "new_case": 27,
        "total_case": 1646,
        "new_case_excludeabroad": 27,
        "total_case_excludeabroad": 1646,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ลำปาง",
        "new_case": 3,
        "total_case": 173,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 173,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "มุกดาหาร",
        "new_case": 1,
        "total_case": 84,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 84,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "บึงกาฬ",
        "new_case": 1,
        "total_case": 57,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 57,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "นครปฐม",
        "new_case": 1,
        "total_case": 250,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 250,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ลพบุรี",
        "new_case": 2,
        "total_case": 126,
        "new_case_excludeabroad": 2,
        "total_case_excludeabroad": 126,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "นครสวรรค์",
        "new_case": 6,
        "total_case": 501,
        "new_case_excludeabroad": 6,
        "total_case_excludeabroad": 501,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สมุทรสาคร",
        "new_case": 6,
        "total_case": 602,
        "new_case_excludeabroad": 6,
        "total_case_excludeabroad": 602,
        "new_death": 0,
        "total_death": 12,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "พระนครศรีอยุธยา",
        "new_case": 1,
        "total_case": 268,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 268,
        "new_death": 0,
        "total_death": 6,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "กาญจนบุรี",
        "new_case": 1,
        "total_case": 65,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 65,
        "new_death": 0,
        "total_death": 12,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "นครราชสีมา",
        "new_case": 21,
        "total_case": 1865,
        "new_case_excludeabroad": 21,
        "total_case_excludeabroad": 1865,
        "new_death": 0,
        "total_death": 4,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สุพรรณบุรี",
        "new_case": 3,
        "total_case": 327,
        "new_case_excludeabroad": 3,
        "total_case_excludeabroad": 327,
        "new_death": 0,
        "total_death": 11,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "กรุงเทพมหานคร",
        "new_case": 299,
        "total_case": 6409,
        "new_case_excludeabroad": 299,
        "total_case_excludeabroad": 6409,
        "new_death": 0,
        "total_death": 17,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "สมุทรสงคราม",
        "new_case": 1,
        "total_case": 102,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 102,
        "new_death": 0,
        "total_death": 4,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "หนองบัวลำภู",
        "new_case": 1,
        "total_case": 78,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 78,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ชุมพร",
        "new_case": 4,
        "total_case": 1131,
        "new_case_excludeabroad": 4,
        "total_case_excludeabroad": 1131,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "อุบลราชธานี",
        "new_case": 4,
        "total_case": 789,
        "new_case_excludeabroad": 4,
        "total_case_excludeabroad": 789,
        "new_death": 0,
        "total_death": 3,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "เชียงใหม่",
        "new_case": 14,
        "total_case": 1006,
        "new_case_excludeabroad": 14,
        "total_case_excludeabroad": 1006,
        "new_death": 1,
        "total_death": 4,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ตาก",
        "new_case": 0,
        "total_case": 341,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 341,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "มหาสารคาม",
        "new_case": 0,
        "total_case": 40,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 40,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ลำพูน",
        "new_case": 0,
        "total_case": 122,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 122,
        "new_death": 0,
        "total_death": 1,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "น่าน",
        "new_case": 0,
        "total_case": 216,
        "new_case_excludeabroad": 0,
        "total_case_excludeabroad": 216,
        "new_death": 0,
        "total_death": 2,
        "update_date": "2024-09-01 19:17:04"
    },
    {
        "year": 2024,
        "weeknum": 34,
        "province": "ตรัง",
        "new_case": 1,
        "total_case": 357,
        "new_case_excludeabroad": 1,
        "total_case_excludeabroad": 357,
        "new_death": 0,
        "total_death": 0,
        "update_date": "2024-09-01 19:17:04"
    }
]

const covidDeath = database.filter(function (element, index) {
    return element.total_death > 5 && element.province !== 'ทั้งประเทศ'
})

const covidDeathOnlyProvince = database.map(function (element, index) {
    return ({
        province: element.province,
        total_Death: element.total_death
    })
})

console.log(covidDeathOnlyProvince)

const news = {
    "status": "success",
    "totalResults": 1538,
    "results": [
        {
            "article_id": "6b044b5fbb8807d8b97b3f02e4971b78",
            "title": "‘มาดามแพ’ ยกนิ้วโป้ง! ให้รอฟังการแถลงดิจิทัลวอลเล็ต",
            "link": "https://www.thaipost.net/politics-news/653684/",
            "keywords": [
                "นายกฯ",
                "ดิจิทัลวอลเล็ต",
                "แพทองธาร ชินวัตร",
                "แถลงนโยบาย",
                "มาดามแพ",
                "การเมือง"
            ],
            "creator": [
                "พี่ฉัตร"
            ],
            "video_url": null,
            "description": "ที่อาคารชินวัตร 3 น.ส.แพทองธาร ชินวัตร นายกรัฐมนตรี เดินทางเข้าปฏิบัติภารกิจเป็นปกติ โดยนายกฯโบกมือทักทายสื่อมวลชนที่The post ‘มาดามแพ’ ยกนิ้วโป้ง! ให้รอฟังการแถลงดิจิทัลวอลเล็ต appeared first on .",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-10 04:30:34",
            "pubDateTZ": "UTC",
            "image_url": "https://storage-wp.thaipost.net/2024/09/crmvTki-3.jpg",
            "source_id": "thaipost",
            "source_priority": 504046,
            "source_name": "Thai Post",
            "source_url": "https://www.thaipost.net",
            "source_icon": "https://i.bytvi.com/domain_icons/thaipost.jpg",
            "language": "thai",
            "country": [
                "thailand"
            ],
            "category": [
                "top"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "d8433374753d18e606068ed240aefd23",
            "title": "มาไม่อั้น FORD เปิดรับจอง EVEREST V6 PLATINUM ไม่จํากัดจํานวน",
            "link": "https://www.thairath.co.th/news/auto/news/2813495",
            "keywords": null,
            "creator": null,
            "video_url": null,
            "description": "Ford เปิดจอง Everest V6 Platinum ล็อตใหม่ไม่จํากัดจํานวน พร้อมกันทั่วประเทศ 17 กันยายนนี้",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-10 04:30:00",
            "pubDateTZ": "UTC",
            "image_url": "https://static.thairath.co.th/media/Kg2lj2gY7z4zNnRd7SuB6xPcamQvNK9gSA5.jpg",
            "source_id": "thairath",
            "source_priority": 44507,
            "source_name": "Thairath",
            "source_url": "https://www.thairath.co.th",
            "source_icon": "https://i.bytvi.com/domain_icons/thairath.png",
            "language": "thai",
            "country": [
                "thailand"
            ],
            "category": [
                "top"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "7277dee19018de485878825672ec2881",
            "title": "ณวัฒน์ แฉต่อ กามิน ค่าตัวแพงกว่าดาราเบอร์หนึ่ง 3 คน ครั้งนี้ถือเป็นบทเรียน",
            "link": "https://www.thairath.co.th/entertain/news/2813491",
            "keywords": null,
            "creator": null,
            "video_url": null,
            "description": "ไม่จบง่ายๆ สําหรับเรื่องราวของ กามิน ติ๊กต่อกเกอร์คนดัง ที่กําลังเป็นประเด็นดราม่าร้อนในขณะนี้ เพราะล่าสุด ณวัฒน์ อิสระไกรศีล",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-10 04:29:21",
            "pubDateTZ": "UTC",
            "image_url": "https://static.thairath.co.th/media/CiHZjUdJ5HPNXJ92O0egbTqA4UmE8wsibA.jpg",
            "source_id": "thairath",
            "source_priority": 44507,
            "source_name": "Thairath",
            "source_url": "https://www.thairath.co.th",
            "source_icon": "https://i.bytvi.com/domain_icons/thairath.png",
            "language": "thai",
            "country": [
                "thailand"
            ],
            "category": [
                "entertainment"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "6d1846279b08d2518db4ce545e60f1e8",
            "title": "“ศิริกัญญา” หวังดิจิทัลวอลเล็ตแบ่งจ่าย 2 รอบไม่ใช่เรื่องจริง",
            "link": "https://www.innnews.co.th/news/politics/news_773225/",
            "keywords": [
                "ภูมิธรรม",
                "ศิริกัญญา",
                "การเมือง",
                "ดิจิทัลวอลเล็ต",
                "เศรษฐกิจ",
                "ข่าว",
                "innnews",
                "รัฐบาล",
                "breakingnews",
                "ไม่พลาดทุกเรื่องอินเทรนด์"
            ],
            "creator": [
                "npakat_k"
            ],
            "video_url": null,
            "description": "“ศิริกัญญา” หวังดิจิทัลวอลเล็ตแบ่งจ่าย2 รอบตาม”ภูมิธรรม”ไม่ใช่เรื่องจริง แซะงบฯ68 ผ่านสภาแล้ว",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-10 04:28:24",
            "pubDateTZ": "UTC",
            "image_url": "https://www.innnews.co.th/wp-content/uploads/2024/09/%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B8%A7%E0%B8%AD%E0%B8%A5%E0%B9%80%E0%B8%A5%E0%B9%87%E0%B8%95.jpg",
            "source_id": "innnews",
            "source_priority": 1978197,
            "source_name": "Inn News",
            "source_url": "https://www.innnews.co.th",
            "source_icon": "https://i.bytvi.com/domain_icons/innnews.png",
            "language": "thai",
            "country": [
                "thailand"
            ],
            "category": [
                "politics"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "4eeee6a5c0512587cad223c92226a2ba",
            "title": "‘ภูมิธรรม’ พร้อมแจกเงินหมื่นกลุ่มเปราะบาง ก.ย. นี้ ยันซื้อสินค้าอะไร ที่ไหนก็ได้",
            "link": "https://www.thebangkokinsight.com/news/business/economics/1381312/",
            "keywords": [
                "economics",
                "ดิจิทัลวอลเล็ต",
                "กระทรวงการคลัง",
                "นายกรัฐมนตรี",
                "เงินดิจิตอล",
                "คลัง",
                "จุลพันธ์",
                "เงินดิจิทัล10000บาท",
                "ภูมิธรรม",
                "เงินดิจิทัลวอลเล็ต",
                "เงินดิจิทัล",
                "แจกเงินหมื่น",
                "เงินดิจิทัล1หมื่นบาท",
                "แพทองธาร",
                "กลุ่มเปราะบาง",
                "โครงการดิจิทัลวอลเล็ต"
            ],
            "creator": [
                "The Bangkok Insight Editorial Team"
            ],
            "video_url": null,
            "description": "“ภูมิธรรม” เผยประชุม ครม.นัดแรก 17 กันยายน [...]",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-10 04:27:04",
            "pubDateTZ": "UTC",
            "image_url": "https://www.thebangkokinsight.com/wp-content/uploads/2024/09/%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B8%A7%E0%B8%AD%E0%B8%A5%E0%B9%80%E0%B8%A5%E0%B9%87%E0%B8%95-10967001-700x394.jpg",
            "source_id": "thebangkokinsight",
            "source_priority": 461737,
            "source_name": "The Bangkok Insight",
            "source_url": "https://www.thebangkokinsight.com",
            "source_icon": "https://i.bytvi.com/domain_icons/thebangkokinsight.png",
            "language": "thai",
            "country": [
                "thailand"
            ],
            "category": [
                "business"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "071386eccbc468532824843d3242f1c0",
            "title": "MOE has taken legal action against contractors over Mobile Guardian cybersecurity breach: Chan Chun Sing",
            "link": "https://www.channelnewsasia.com/singapore/mobile-guardian-cybersecurity-breach-attack-legal-action-contractors-chan-chun-sing-4597791",
            "keywords": [
                "singapore"
            ],
            "creator": null,
            "video_url": null,
            "description": "Data from 13,000 personal learning devices was wiped out in August. Less than 5 per cent of users were unable to recover all their data because the devices were not backed up.",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-10 04:26:33",
            "pubDateTZ": "UTC",
            "image_url": "https://onecms-res.cloudinary.com/image/upload/s--txktpXh5--/c_fill,h_900,w_1600/fl_relative,g_south_east,l_mediacorp:cna:watermark:2021-08:cna,w_0.1/f_auto,q_auto/v1/mediacorp/cna/image/2024/09/09/mobile_guardian_moe_contract_termination.png?itok=PNUaCuiw",
            "source_id": "channelnewsasia",
            "source_priority": 37829,
            "source_name": "Cna",
            "source_url": "https://www.channelnewsasia.com",
            "source_icon": "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
            "language": "english",
            "country": [
                "georgia",
                "yemen",
                "afghanistan",
                "cyprus",
                "india",
                "singapore",
                "saudi arabia",
                "maldives",
                "japan",
                "united arab emirates",
                "malaysia",
                "china",
                "south korea",
                "north korea",
                "taiwan",
                "thailand",
                "pakistan",
                "mongolia",
                "brunei",
                "lebanon",
                "indonesia",
                "kyrgyzstan",
                "syria",
                "israel",
                "bhutan",
                "iran",
                "turkey",
                "armenia",
                "qatar",
                "philippines",
                "hong kong",
                "kazakhstan",
                "iraq",
                "bangladesh",
                "laos",
                "vietnam",
                "timor-leste",
                "kuwait",
                "myanmar",
                "azerbaijan",
                "jordan",
                "nepal",
                "sri lanka",
                "uzbekistan",
                "turkmenistan",
                "macau",
                "bahrain",
                "cambodia",
                "tajikistan",
                "romania"
            ],
            "category": [
                "top"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "af5b828977ad39902ea2211f45446df3",
            "title": "Driver who fled after colliding with motorcycle in fatal BKE accident jailed",
            "link": "https://www.channelnewsasia.com/singapore/driver-jailed-bke-accident-motorcyclist-died-4597816",
            "keywords": [
                "singapore"
            ],
            "creator": null,
            "video_url": null,
            "description": "The court heard that Pua Yui Loon had been speeding at 141kmh when he tried to squeeze past a motorcycle on the same lane.",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-10 04:26:04",
            "pubDateTZ": "UTC",
            "image_url": "https://onecms-res.cloudinary.com/image/upload/s--9l7MYXAV--/c_fill,h_900,w_1600/fl_relative,g_south_east,l_mediacorp:cna:watermark:2021-08:cna,w_0.1/f_auto,q_auto/v1/mediacorp/cna/image/2024/09/10/pua%20yui%20loon%203.jpg?itok=TzC6f4fS",
            "source_id": "channelnewsasia",
            "source_priority": 37829,
            "source_name": "Cna",
            "source_url": "https://www.channelnewsasia.com",
            "source_icon": "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
            "language": "english",
            "country": [
                "georgia",
                "yemen",
                "afghanistan",
                "cyprus",
                "india",
                "singapore",
                "saudi arabia",
                "maldives",
                "japan",
                "united arab emirates",
                "malaysia",
                "china",
                "south korea",
                "north korea",
                "taiwan",
                "thailand",
                "pakistan",
                "mongolia",
                "brunei",
                "lebanon",
                "indonesia",
                "kyrgyzstan",
                "syria",
                "israel",
                "bhutan",
                "iran",
                "turkey",
                "armenia",
                "qatar",
                "philippines",
                "hong kong",
                "kazakhstan",
                "iraq",
                "bangladesh",
                "laos",
                "vietnam",
                "timor-leste",
                "kuwait",
                "myanmar",
                "azerbaijan",
                "jordan",
                "nepal",
                "sri lanka",
                "uzbekistan",
                "turkmenistan",
                "macau",
                "bahrain",
                "cambodia",
                "tajikistan",
                "oman"
            ],
            "category": [
                "top"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "8bc55f199e74b06fc3d2b345b6cf88d2",
            "title": "เผยเบื้องหลังอื้อฉาว แผนสกปรกขโมยมงกุฏมิสยูนิเวิร์สฟิจิ",
            "link": "https://www.thairath.co.th/news/foreign/2813348",
            "keywords": null,
            "creator": null,
            "video_url": null,
            "description": "การประกวดนางงามจักรวาลครั้งแรกของฟิจิในรอบกว่า 40 ปี กําลังเผชิญเรื่องอื้อฉาว จากข้อกล่าวหาที่ดูแปลกประหลาด",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-10 04:25:22",
            "pubDateTZ": "UTC",
            "image_url": "https://static.thairath.co.th/media/CiHZjUdJ5HPNXJ92O0egbafuy1LFvUVBN2.jpg",
            "source_id": "thairath",
            "source_priority": 44507,
            "source_name": "Thairath",
            "source_url": "https://www.thairath.co.th",
            "source_icon": "https://i.bytvi.com/domain_icons/thairath.png",
            "language": "thai",
            "country": [
                "thailand"
            ],
            "category": [
                "top"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "64d9326476b6e46d8124d9027827ca81",
            "title": "หนิง ปณิตา ตอบปมโพสต์ข้อความ ก่อนจะเมาท์ใครดูตัวเองให้ดีๆ ก่อน",
            "link": "https://www.thairath.co.th/entertain/celeb/2813498",
            "keywords": null,
            "creator": null,
            "video_url": null,
            "description": "หนิง ปณิตา ตอบแล้วหลังโพสต์ข้อความ ก่อนเสียเวลาเมาท์ใคร เอาเวลานั้นไปดูตัวเองให้ดีก่อน หมายถึงคนใกล้ตัว แค่อยากเตือนสติคนบางคน ลั่นเดี๋ยวนี้มูฟออนเร็วมาก",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-10 04:24:26",
            "pubDateTZ": "UTC",
            "image_url": "https://static.thairath.co.th/media/CiHZjUdJ5HPNXJ92O0egbTqAJ9c4nscjn6.jpg",
            "source_id": "thairath",
            "source_priority": 44507,
            "source_name": "Thairath",
            "source_url": "https://www.thairath.co.th",
            "source_icon": "https://i.bytvi.com/domain_icons/thairath.png",
            "language": "thai",
            "country": [
                "thailand"
            ],
            "category": [
                "entertainment"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "86d0c213d088c0c2fe48384be7fea48a",
            "title": "America’s kryptonite? Just say China ‘gray zone’",
            "link": "https://asiatimes.com/2024/09/americas-kryptonite-just-say-china-gray-zone/",
            "keywords": [
                "south china sea",
                "opinion",
                "china gray zone tactics",
                "china",
                "philippines",
                "us-china war",
                "block 2"
            ],
            "creator": null,
            "video_url": null,
            "description": "You may have seen the recent headlines like “Philippines and Chinese coast guard ships collide in South China Sea” and “China, Philippines accuse each other of ramming ships in South China Sea.” Seeing those headlines, you might think what happened was an incident in which both parties – or no one – was at fault. [...]The post America’s kryptonite? Just say China ‘gray zone’ appeared first on Asia Times.",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-10 04:24:03",
            "pubDateTZ": "UTC",
            "image_url": "https://i0.wp.com/asiatimes.com/wp-content/uploads/2024/09/1_2024-03-05_22-16-11.jpg?fit=1024%2C683&ssl=1",
            "source_id": "asiatimes",
            "source_priority": 67073,
            "source_name": "Asia Times",
            "source_url": "https://asiatimes.com",
            "source_icon": "https://i.bytvi.com/domain_icons/asiatimes.png",
            "language": "english",
            "country": [
                "georgia",
                "yemen",
                "afghanistan",
                "cyprus",
                "india",
                "singapore",
                "saudi arabia",
                "maldives",
                "japan",
                "united arab emirates",
                "malaysia",
                "china",
                "south korea",
                "north korea",
                "taiwan",
                "thailand",
                "pakistan",
                "mongolia",
                "brunei",
                "lebanon",
                "indonesia",
                "kyrgyzstan",
                "syria",
                "israel",
                "bhutan",
                "iran",
                "turkey",
                "armenia",
                "qatar",
                "philippines",
                "hong kong",
                "kazakhstan",
                "iraq",
                "bangladesh",
                "laos",
                "vietnam",
                "timor-leste",
                "kuwait",
                "myanmar",
                "azerbaijan",
                "jordan",
                "nepal",
                "oman",
                "sri lanka",
                "uzbekistan",
                "turkmenistan",
                "macau",
                "bahrain",
                "cambodia",
                "tajikistan"
            ],
            "category": [
                "politics"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        }
    ],
    "nextPage": "1725942243644285456"
}

const newsOnlyThaipbs = news.results.filter(function (element, index) {
    return element.language !== 'english' && element.source_id === 'thaipbs'
}).map(function (element, index) {
    return ({
        title: element.title,
        link: element.link,
        description: element.description,
        sorce_id: element.source_id,
        imaga_url: element.image_url
    })
})

console.log(newsOnlyThaipbs)